import { CourseWorkshop } from './CourseWorkshop'
import { useRef, useState } from 'react'
import { ArrowLeftIcon, ArrowRightIcon, BookOpenIcon, CheckCircleIcon, ClockIcon, CopyIcon, FileTextIcon, GraduationCapIcon, ListChecksIcon, StackIcon } from '@phosphor-icons/react'
import type { SharedCourse } from '../../modules/shared-knowledge'
import { courseArtwork, courseTemplates, importCourseTemplate, type CourseTemplate, type TemplateImportProgress } from './courseTemplates'
import './course-catalog.css'

export function CourseCatalog({ courses, role, query, onOpen, onRemove }: { courses: SharedCourse[]; role: 'teacher' | 'student'; query: string; onOpen: (id: string) => void; onRemove: (id: string) => void }) {
  const [preview, setPreview] = useState<CourseTemplate | null>(null)
  const [chapter, setChapter] = useState<number | null>(null)
  const [tab, setTab] = useState<'all' | 'mine' | 'examples'>('all')
  const [importing, setImporting] = useState(false)
  const [error, setError] = useState('')
  const [progress, setProgress] = useState<Record<string, TemplateImportProgress>>({})
  const importLock = useRef(false)
  const [exercise, setExercise] = useState('')
  async function handleImportTemplate(template: CourseTemplate) {
    if (importLock.current) return
    importLock.current = true; setImporting(true); setError('')
    try {
      const id = await importCourseTemplate(template, progress[template.id] ?? { courseId: null, uploaded: 0 }, (next) => setProgress((current) => ({ ...current, [template.id]: next })))
      onOpen(id)
    } catch (reason) { setError(reason instanceof Error ? reason.message : '导入未完成，请重试。') }
    finally { importLock.current = false; setImporting(false) }
  }
  const examples = courseTemplates.filter((item) => `${item.title}${item.category}`.includes(query))
  if (preview) {
    const active = chapter === null ? null : preview.chapters[chapter]
    const currentProgress = progress[preview.id]
    return <section className="course-preview" aria-label="示范课程详情">
      <button type="button" className="courses-page__text-button" disabled={importing} onClick={() => { setPreview(null); setChapter(null); setError('') }}><ArrowLeftIcon size={16} />返回课程目录</button>
      <header className="course-preview__hero"><div><span className="course-catalog__eyebrow">示范课程 / {preview.category}</span><h2>{preview.title}</h2><p>{preview.description}</p><div className="course-catalog__metadata"><span><StackIcon size={15} />{preview.chapters.length} 个单元</span><span><ClockIcon size={15} />{preview.chapters.reduce((sum, item) => sum + item.duration, 0)} 分钟建议课时</span><span>{preview.level}</span></div></div><img className="course-preview__cover-image" src={courseArtwork[preview.id]} alt="" /></header>
      <div className="course-preview__layout"><nav className="course-preview__navigation" aria-label="示范课程章节"><button aria-current={chapter === null ? 'page' : undefined} onClick={() => setChapter(null)}><GraduationCapIcon size={18} />课程概览</button>{preview.chapters.map((item, index) => <button key={item.title} aria-current={chapter === index ? 'page' : undefined} onClick={() => { setChapter(index); setExercise('') }}><span className="course-unit-number">{String(index + 1).padStart(2, '0')}</span><span>{item.title}<small>{item.duration} 分钟 · 阅读与练习</small></span></button>)}<p>原创示范教学材料<br />用于体验课程结构与操作流程</p></nav>
      <main className="course-preview__content">
        {active ? <article><span className="course-catalog__eyebrow">第 {chapter! + 1} 单元 / 共 {preview.chapters.length} 单元</span><h3>{active.title}</h3><div className="course-objective"><ListChecksIcon size={20} /><p>{active.objective}</p></div><div className="course-preview__reading">{active.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><section className="course-exercise"><span className="course-catalog__eyebrow">课堂练习</span><h4>把理解用在一个新问题上</h4><p>{active.exercise}</p><label>我的练习笔记<textarea value={exercise} onChange={(event) => setExercise(event.target.value)} placeholder="记录你的思路，再对照下面的自查要点。" /></label><small>示范区笔记仅在当前单元临时保留，不提交给教师。</small><details><summary>查看自查要点</summary><ul>{active.checklist.map((item) => <li key={item}>{item}</li>)}</ul></details></section><div className="course-preview__footer"><button className="qx-button" disabled={chapter === 0} onClick={() => { setChapter(chapter! - 1); setExercise('') }}>上一单元</button>{chapter! < preview.chapters.length - 1 ? <button className="research-hub__new" onClick={() => { setChapter(chapter! + 1); setExercise('') }}>下一单元<ArrowRightIcon size={16} /></button> : <button className="qx-button" onClick={() => setChapter(null)}>返回课程概览</button>}</div></article> : <>
          <div className="course-section-heading"><h3>课程概览</h3><span>从阅读到实践</span></div><p className="course-preview__intro">{preview.subtitle}。每个单元包含教学目标、阅读材料、课堂练习与自查要点。</p>
          <div className="course-resource-summary"><div><BookOpenIcon size={19} /><strong>{preview.chapters.length}</strong><span>阅读讲义</span></div><div><ListChecksIcon size={19} /><strong>{preview.chapters.length}</strong><span>单元练习</span></div><div><CheckCircleIcon size={19} /><strong>{preview.chapters.reduce((sum, unit) => sum + unit.checklist.length, 0)}</strong><span>自查要点</span></div></div><section className="course-outcomes"><h4>完成课程后，你将能够</h4>{preview.outcomes.map((outcome) => <p key={outcome}><CheckCircleIcon size={18} />{outcome}</p>)}</section>
          <div className="course-section-heading"><h3>课程单元</h3><span>{preview.chapters.length} 个学习单元</span></div><div className="course-unit-list">{preview.chapters.map((item, index) => <button key={item.title} onClick={() => setChapter(index)}><span className="course-unit-number">{String(index + 1).padStart(2, '0')}</span><span><strong>{item.title}</strong><small>{item.objective}</small></span><span className="course-unit-duration">{item.duration} 分钟</span><ArrowRightIcon size={17} /></button>)}</div>
          <CourseWorkshop templateId={preview.id} courseTitle={preview.title} /><div className="course-teaching-plan"><section><h4>适合谁学习</h4><p>{preview.level === '方法进阶' ? '已有基础研究方法知识，希望练习访谈与材料分析的学习者。' : '希望从具体案例理解社会学与研究方法的初学者，无需先修专业课程。'}</p></section><section><h4>学习与评价方式</h4><p>阅读单元讲义后完成练习，依据自查要点检查。用于正式课堂时，由教师设定评价标准、复核并发布反馈。</p></section></div><section className="course-template-action"><div><h4>{role === 'teacher' ? '以这门课程开始你的教学' : '先体验阅读，再进入你的课堂'}</h4><p>{role === 'teacher' ? '复制后将创建你的课程，并导入各单元讲义。你可以编辑课程、备课和分享给学生。' : '示范课程可以直接阅读。正式作业与学习反馈，请进入老师分享给你的课程。'}</p></div>{role === 'teacher' ? <button className="research-hub__new" disabled={importing} onClick={() => void handleImportTemplate(preview)}><CopyIcon size={17} />{importing ? `正在导入 ${currentProgress?.uploaded ?? 0}/${preview.chapters.length}` : currentProgress?.courseId ? '继续导入课程' : '使用此课程模板'}</button> : <button className="research-hub__new" onClick={() => setChapter(0)}>开始第一单元<ArrowRightIcon size={16} /></button>}</section>
        </>}
        {error && <p className="qx-message is-error" role="alert">{error}{currentProgress?.courseId && <button className="courses-page__text-button" onClick={() => onOpen(currentProgress.courseId!)}>打开已创建的课程</button>}</p>}
      </main></div>
    </section>
  }
  return <section className="course-catalog" aria-label="课程目录">
    <header className="course-catalog__intro"><div><span className="course-catalog__eyebrow">群学致知 / 课堂</span><h2>{role === 'teacher' ? '组织课程，连接每一次教学。' : '从课堂出发，建立你的知识。'}</h2><p>{role === 'teacher' ? '集中管理课程资料、备课文稿与作业反馈，也可以从示范课程开始。' : '找到你的课程，阅读单元材料，继续学习并查看教师反馈。'}</p></div><img className="course-catalog__hero-image" src={courseArtwork.library} alt="" /><div className="course-catalog__count"><strong>{courses.length}</strong><span>{role === 'teacher' ? '门我的教学课程' : '门已加入课程'}</span></div></header>
    <nav className="course-catalog__tabs" aria-label="课程目录筛选">{([['all', '全部课程'], ['mine', role === 'teacher' ? '我的教学' : '我的课程'], ['examples', '示范课程']] as const).map(([value, label]) => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{label}<span>{value === 'examples' ? examples.length : value === 'mine' ? courses.length : courses.length + examples.length}</span></button>)}</nav>
    {tab !== 'examples' && <><div className="course-section-heading"><h3>{role === 'teacher' ? '我的教学课程' : '我的课程'}</h3><span>{courses.length} 门课程</span></div>{courses.length ? <div className="course-catalog__grid">{courses.map((course, index) => <article className="course-tile" key={course.id}><div className="course-tile__cover"><span className="course-tile__tag">{course.access === 'unavailable' ? '暂不可用' : role === 'teacher' ? '教学课程' : '已加入'}</span><img src={courseArtwork[['social-research', 'sociological-thinking', 'qualitative-reading'][index % 3]]} alt="" loading="lazy" /><span className="course-tile__cover-title">{course.name || '课程'}</span></div><div className="course-tile__body"><h3>{course.name || '已添加的课程'}</h3><p>{course.description || (course.access === 'unavailable' ? '此课程已停止共享或被删除。' : '集中管理课程资料与教学活动。')}</p><div className="course-tile__meta"><FileTextIcon size={15} />{course.readyDocumentCount} 份可用资料<span>{course.sharingEnabled ? '课程已共享' : '私有课程'}</span></div>{course.access === 'unavailable' ? <button className="qx-button" onClick={() => onRemove(course.id)}>移除课程</button> : <button className="course-tile__open" aria-label={`打开课程 ${course.name}`} onClick={() => onOpen(course.id)}>进入课程<ArrowRightIcon size={18} /></button>}</div></article>)}</div> : <div className="course-catalog__empty"><BookOpenIcon size={24} /><div><strong>{query ? '没有找到相关课程' : role === 'teacher' ? '开始你的第一门课程' : '还没有加入课程'}</strong><p>{role === 'teacher' ? '创建课程，或选择下方示范模板导入完整讲义。' : '使用老师的分享链接添加课程，也可以先体验下方示范课程。'}</p></div></div>}</>}
    {tab !== 'mine' && <><div className="course-section-heading"><div><h3>示范课程</h3><p>阅读、方法训练与成果修订</p></div><span>原创教学示例 · 可阅读{role === 'teacher' ? ' · 可复制' : ''}</span></div><div className="course-catalog__grid">{examples.map((template) => <article className="course-tile" key={template.id}><div className="course-tile__cover" data-variant={template.id}><span className="course-tile__tag">{template.category}</span><img src={courseArtwork[template.id]} alt="" loading="lazy" /><span className="course-tile__cover-title">{template.subtitle}</span></div><div className="course-tile__body"><span className="course-catalog__eyebrow">{template.level} · 示范课程</span><h3>{template.title}</h3><p>{template.description}</p><ul className="course-tile__syllabus">{template.chapters.slice(0, 3).map((unit) => <li key={unit.title}><CheckCircleIcon size={13} />{unit.title}</li>)}</ul><div className="course-tile__meta"><StackIcon size={15} />{template.chapters.length} 个单元<span>{template.chapters.reduce((total, unit) => total + unit.duration, 0)} 分钟阅读讨论 · {template.chapters.length} 项练习</span></div><button className="course-tile__open" aria-label={`预览课程 ${template.title}`} onClick={() => { setPreview(template); setChapter(null) }}>浏览课程<ArrowRightIcon size={18} /></button></div></article>)}</div>{!examples.length && <p className="courses-page__hint">没有匹配的示范课程。</p>}</>}
  </section>
}
