from typing import Protocol
from uuid import UUID

from qunxue_api.modules.research_analysis.domain import (
    AnalysisAnnotation,
    AnalysisCode,
    AnalysisMemo,
    AnalysisWriteRequest,
    CaseComparison,
)


class ResearchAnalysisRepository(Protocol):
    def reserve_write(self, value: AnalysisWriteRequest) -> AnalysisWriteRequest: ...
    def get_write(
        self,
        *,
        user_id: UUID,
        task_id: UUID,
        namespace: str,
        idempotency_key: str,
    ) -> AnalysisWriteRequest | None: ...
    def add_annotation(self, value: AnalysisAnnotation) -> AnalysisAnnotation: ...
    def add_code(self, value: AnalysisCode) -> AnalysisCode: ...
    def add_memo(self, value: AnalysisMemo) -> AnalysisMemo: ...
    def add_comparison(self, value: CaseComparison) -> CaseComparison: ...
    def get_annotation(
        self, annotation_id: UUID, *, user_id: UUID, task_id: UUID
    ) -> AnalysisAnnotation | None: ...
    def get_code(self, code_id: UUID, *, user_id: UUID, task_id: UUID) -> AnalysisCode | None: ...
    def get_memo(self, memo_id: UUID, *, user_id: UUID, task_id: UUID) -> AnalysisMemo | None: ...
    def get_comparison(
        self, comparison_id: UUID, *, user_id: UUID, task_id: UUID
    ) -> CaseComparison | None: ...
    def list_annotations(
        self, *, user_id: UUID, task_id: UUID
    ) -> tuple[AnalysisAnnotation, ...]: ...
    def list_codes(self, *, user_id: UUID, task_id: UUID) -> tuple[AnalysisCode, ...]: ...
    def list_memos(self, *, user_id: UUID, task_id: UUID) -> tuple[AnalysisMemo, ...]: ...
    def list_comparisons(self, *, user_id: UUID, task_id: UUID) -> tuple[CaseComparison, ...]: ...
