from typing import Protocol
from uuid import UUID

from qunxue_api.modules.research_analysis.domain import (
    AnalysisAnnotation,
    AnalysisCode,
    AnalysisMemo,
    AnalysisWriteRequest,
    CaseComparison,
)
from qunxue_api.modules.research_analysis.qualitative_workspace import (
    AnalysisCaseProfile,
    AnalysisMemoLink,
    AnalysisTheme,
    CaseThemeMatrixCell,
    CodebookEntry,
    MethodPresetSelection,
)


class ResearchAnalysisRepository(Protocol):
    def reserve_write(self, value: AnalysisWriteRequest) -> AnalysisWriteRequest: ...
    def get_write(
        self,
        *,
        user_id: UUID,
        task_id: UUID,
        namespace: str,
        idempotency_key: str,
    ) -> AnalysisWriteRequest | None: ...
    def add_annotation(self, value: AnalysisAnnotation) -> AnalysisAnnotation: ...
    def add_code(self, value: AnalysisCode) -> AnalysisCode: ...
    def add_memo(self, value: AnalysisMemo) -> AnalysisMemo: ...
    def add_comparison(self, value: CaseComparison) -> CaseComparison: ...
    def get_annotation(
        self, annotation_id: UUID, *, user_id: UUID, task_id: UUID
    ) -> AnalysisAnnotation | None: ...
    def get_code(self, code_id: UUID, *, user_id: UUID, task_id: UUID) -> AnalysisCode | None: ...
    def get_memo(self, memo_id: UUID, *, user_id: UUID, task_id: UUID) -> AnalysisMemo | None: ...
    def get_comparison(
        self, comparison_id: UUID, *, user_id: UUID, task_id: UUID
    ) -> CaseComparison | None: ...
    def list_annotations(
        self, *, user_id: UUID, task_id: UUID
    ) -> tuple[AnalysisAnnotation, ...]: ...
    def list_codes(self, *, user_id: UUID, task_id: UUID) -> tuple[AnalysisCode, ...]: ...
    def list_memos(self, *, user_id: UUID, task_id: UUID) -> tuple[AnalysisMemo, ...]: ...
    def list_comparisons(self, *, user_id: UUID, task_id: UUID) -> tuple[CaseComparison, ...]: ...
    def add_codebook_entry(self, value: CodebookEntry) -> CodebookEntry: ...
    def get_codebook_entry(
        self, code_id: UUID, *, user_id: UUID, task_id: UUID
    ) -> CodebookEntry | None: ...
    def list_codebook_entries(
        self, *, user_id: UUID, task_id: UUID
    ) -> tuple[CodebookEntry, ...]: ...
    def add_theme(self, value: AnalysisTheme) -> AnalysisTheme: ...
    def get_theme(
        self, theme_id: UUID, *, user_id: UUID, task_id: UUID
    ) -> AnalysisTheme | None: ...
    def list_themes(self, *, user_id: UUID, task_id: UUID) -> tuple[AnalysisTheme, ...]: ...
    def add_memo_link(self, value: AnalysisMemoLink) -> AnalysisMemoLink: ...
    def list_memo_links(self, *, user_id: UUID, task_id: UUID) -> tuple[AnalysisMemoLink, ...]: ...
    def add_case_profile(self, value: AnalysisCaseProfile) -> AnalysisCaseProfile: ...
    def get_case_profile(
        self, profile_id: UUID, *, user_id: UUID, task_id: UUID
    ) -> AnalysisCaseProfile | None: ...
    def list_case_profiles(
        self, *, user_id: UUID, task_id: UUID
    ) -> tuple[AnalysisCaseProfile, ...]: ...
    def add_matrix_cell(self, value: CaseThemeMatrixCell) -> CaseThemeMatrixCell: ...
    def list_matrix_cells(
        self, *, user_id: UUID, task_id: UUID
    ) -> tuple[CaseThemeMatrixCell, ...]: ...
    def add_method_selection(self, value: MethodPresetSelection) -> MethodPresetSelection: ...
    def get_method_selection(
        self, *, user_id: UUID, task_id: UUID
    ) -> MethodPresetSelection | None: ...
