"""Public material domain boundary."""

from qunxue_api.modules.research_materials.domain import (
    MaterialBlock,
    MaterialFormat,
    MaterialKind,
    MaterialLocator,
    MaterialParseVersion,
    MaterialReparseRequest,
    MaterialStatus,
    ParsedMaterial,
    ResearchMaterial,
)
from qunxue_api.modules.research_materials.errors import (
    DoiMetadataUnavailable,
    MaterialDeleted,
    MaterialIdempotencyConflict,
    MaterialNotFound,
    MaterialOwnershipError,
    MaterialParseError,
    MaterialVersionConflict,
    ResearchMaterialError,
    UnsupportedMaterialFormat,
)
from qunxue_api.modules.research_materials.literature_exchange import (
    export_literature_entries,
    import_literature_entries,
)
from qunxue_api.modules.research_materials.ports import ResearchMaterialRepository
from qunxue_api.modules.research_materials.professional import (
    CaseAttributeValue,
    ConsentScope,
    DeidentificationStatus,
    DoiMetadataCandidate,
    ImportedLiteratureRecord,
    LiteratureDuplicateHint,
    LiteratureEntry,
    LiteratureExchangeFormat,
    MaterialArchiveInventory,
    MaterialArchiveProfile,
    MaterialBatch,
    MaterialCollection,
    MaterialRelation,
    MaterialRelationType,
    ModelProcessingScope,
    ProfessionalMaterialArchive,
    ProfessionalMaterialArchiveView,
    ResearchCase,
    ResearchRole,
    ResearchStage,
    SensitivityLevel,
    normalize_doi,
)
from qunxue_api.modules.research_materials.professional_ports import (
    DoiMetadataResolver,
    ProfessionalMaterialRepository,
)
from qunxue_api.modules.research_materials.service import ResearchMaterialService

__all__ = [
    "DoiMetadataUnavailable",
    "MaterialBlock",
    "MaterialDeleted",
    "MaterialFormat",
    "MaterialIdempotencyConflict",
    "MaterialKind",
    "MaterialLocator",
    "MaterialNotFound",
    "MaterialOwnershipError",
    "MaterialParseError",
    "MaterialParseVersion",
    "MaterialReparseRequest",
    "MaterialStatus",
    "ParsedMaterial",
    "MaterialVersionConflict",
    "ResearchMaterial",
    "ResearchMaterialError",
    "ResearchMaterialRepository",
    "ResearchMaterialService",
    "UnsupportedMaterialFormat",
    "CaseAttributeValue",
    "ConsentScope",
    "DeidentificationStatus",
    "DoiMetadataCandidate",
    "DoiMetadataResolver",
    "ImportedLiteratureRecord",
    "LiteratureEntry",
    "LiteratureDuplicateHint",
    "LiteratureExchangeFormat",
    "MaterialArchiveProfile",
    "MaterialArchiveInventory",
    "MaterialBatch",
    "MaterialCollection",
    "MaterialRelation",
    "MaterialRelationType",
    "ModelProcessingScope",
    "ProfessionalMaterialArchive",
    "ProfessionalMaterialArchiveView",
    "ProfessionalMaterialRepository",
    "ResearchCase",
    "ResearchRole",
    "ResearchStage",
    "SensitivityLevel",
    "export_literature_entries",
    "import_literature_entries",
    "normalize_doi",
]
